name: Update Add-on Version

on:
  repository_dispatch:
    types: [backend_release]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout add-on repo
        uses: actions/checkout@v4

      - name: Set version from payload
        run: |
          VERSION='${{ github.event.client_payload.version }}'
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update config.yaml version
        run: |
          VERSION="${{ env.VERSION }}"
          echo "Usando versão $VERSION"
          sed -i "s/version: \".*\"/version: \"$VERSION\"/" config.yaml
          cat config.yaml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "addon-bot"
          git config user.email "addon-bot@users.noreply.github.com"

          if git diff --quiet; then
            echo "Nenhuma mudança para commitar."
            exit 0
          fi

          git commit -am "chore: bump add-on version to ${{ env.VERSION }}"
          git push